source 'https://rubygems.org'

gem 'rails', '4.1.0'
gem 'pg'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring', group: :development
gem 'byebug', group: :development
gem 'active_model_serializers'
gem 'bcrypt-ruby'
